# Generated by Django 4.1.1 on 2022-10-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
